version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - nestjs
volumes:
  psql_data:
    driver: local
networks:
   nestjs:
